var json_destinasi_woman_titik_2 = {
"type": "FeatureCollection",
"name": "destinasi_woman_titik_2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OID_": "0", "Name": "Gunung Api Purba Nglanggeran", "FolderPath": "TRAIL WOMAN\/Directions from Gunung Api Purba Nglanggeran, Nglanggeran Kulon, Nglanggeran, Gunung Kidul Regency, Special Region of Yogyakarta to ViaVia Jogja, Jalan Prawirotaman, Brontokusuman, Yogyakarta City, Special Region of Yogyakarta", "SymbolID": "0", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 110.537853300000052, -7.842837699999961 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "Purba Ayu Spa House", "FolderPath": "TRAIL WOMAN\/Directions from Gunung Api Purba Nglanggeran, Nglanggeran Kulon, Nglanggeran, Gunung Kidul Regency, Special Region of Yogyakarta to ViaVia Jogja, Jalan Prawirotaman, Brontokusuman, Yogyakarta City, Special Region of Yogyakarta", "SymbolID": "1", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 110.538103800000044, -7.848154499999964 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "Pawon Purba and Homestay", "FolderPath": "TRAIL WOMAN\/Directions from Gunung Api Purba Nglanggeran, Nglanggeran Kulon, Nglanggeran, Gunung Kidul Regency, Special Region of Yogyakarta to ViaVia Jogja, Jalan Prawirotaman, Brontokusuman, Yogyakarta City, Special Region of Yogyakarta", "SymbolID": "2", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 110.534902300000056, -7.844446 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "JogJamu", "FolderPath": "TRAIL WOMAN\/Directions from Gunung Api Purba Nglanggeran, Nglanggeran Kulon, Nglanggeran, Gunung Kidul Regency, Special Region of Yogyakarta to ViaVia Jogja, Jalan Prawirotaman, Brontokusuman, Yogyakarta City, Special Region of Yogyakarta", "SymbolID": "3", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 110.390047400000071, -7.823676499999976 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "Pasar Beringharjo", "FolderPath": "TRAIL WOMAN\/Directions from Gunung Api Purba Nglanggeran, Nglanggeran Kulon, Nglanggeran, Gunung Kidul Regency, Special Region of Yogyakarta to ViaVia Jogja, Jalan Prawirotaman, Brontokusuman, Yogyakarta City, Special Region of Yogyakarta", "SymbolID": "4", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 110.367455, -7.798715099999981 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "ViaVia Jogja", "FolderPath": "TRAIL WOMAN\/Directions from Gunung Api Purba Nglanggeran, Nglanggeran Kulon, Nglanggeran, Gunung Kidul Regency, Special Region of Yogyakarta to ViaVia Jogja, Jalan Prawirotaman, Brontokusuman, Yogyakarta City, Special Region of Yogyakarta", "SymbolID": "5", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 110.371517200000085, -7.819252499999948 ] } }
]
}
